export const properties = [
    {
      name: "Property 1",
      description: "Description of Property 1",
      location: "Location of Property 1",
      views: "Views of Property 1",
      technologies: "Technologies of Property 1",
      rooms: 3,
      "extra amenities": "Amenities of Property 1",
      "special services": true,
      price: 2000,
      ID: "c4a31f70-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 2",
      description: "Description of Property 2",
      location: "Location of Property 2",
      views: "Views of Property 2",
      technologies: "Technologies of Property 2",
      rooms: 4,
      "extra amenities": "Amenities of Property 2",
      "special services": false,
      price: 1500,
      ID: "c4a321a0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 3",
      description: "Description of Property 3",
      location: "Location of Property 3",
      views: "Views of Property 3",
      technologies: "Technologies of Property 3",
      rooms: 2,
      "extra amenities": "Amenities of Property 3",
      "special services": true,
      price: 1800,
      ID: "c4a32310-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 4",
      description: "Description of Property 4",
      location: "Location of Property 4",
      views: "Views of Property 4",
      technologies: "Technologies of Property 4",
      rooms: 5,
      "extra amenities": "Amenities of Property 4",
      "special services": true,
      price: 2200,
      ID: "c4a32440-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 5",
      description: "Description of Property 5",
      location: "Location of Property 5",
      views: "Views of Property 5",
      technologies: "Technologies of Property 5",
      rooms: 3,
      "extra amenities": "Amenities of Property 5",
      "special services": false,
      price: 1700,
      ID: "c4a32550-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 6",
      description: "Description of Property 6",
      location: "Location of Property 6",
      views: "Views of Property 6",
      technologies: "Technologies of Property 6",
      rooms: 4,
      "extra amenities": "Amenities of Property 6",
      "special services": true,
      price: 1900,
      ID: "c4a32670-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 7",
      description: "Description of Property 7",
      location: "Location of Property 7",
      views: "Views of Property 7",
      technologies: "Technologies of Property 7",
      rooms: 2,
      "extra amenities": "Amenities of Property 7",
      "special services": true,
      price: 1800,
      ID: "c4a327a0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 8",
      description: "Description of Property 8",
      location: "Location of Property 8",
      views: "Views of Property 8",
      technologies: "Technologies of Property 8",
      rooms: 5,
      "extra amenities": "Amenities of Property 8",
      "special services": false,
      price: 2300,
      ID: "c4a328e0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 9",
      description: "Description of Property 9",
      location: "Location of Property 9",
      views: "Views of Property 9",
      technologies: "Technologies of Property 9",
      rooms: 3,
      "extra amenities": "Amenities of Property 9",
      "special services": false,
      price: 1600,
      ID: "c4a32a00-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 10",
      description: "Description of Property 10",
      location: "Location of Property 10",
      views: "Views of Property 10",
      technologies: "Technologies of Property 10",
      rooms: 4,
      "extra amenities": "Amenities of Property 10",
      "special services": true,
      price: 2100,
      ID: "c4a32b20-c3f1-11eb-8529-0242ac130003",
    },
    // Continuar hasta Property 30...
    {
      name: "Property 11",
      description: "Description of Property 11",
      location: "Location of Property 11",
      views: "Views of Property 11",
      technologies: "Technologies of Property 11",
      rooms: 2,
      "extra amenities": "Amenities of Property 11",
      "special services": true,
      price: 1800,
      ID: "c4a32c30-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 12",
      description: "Description of Property 12",
      location: "Location of Property 12",
      views: "Views of Property 12",
      technologies: "Technologies of Property 12",
      rooms: 5,
      "extra amenities": "Amenities of Property 12",
      "special services": false,
      price: 2200,
      ID: "c4a32d50-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 13",
      description: "Description of Property 13",
      location: "Location of Property 13",
      views: "Views of Property 13",
      technologies: "Technologies of Property 13",
      rooms: 3,
      "extra amenities": "Amenities of Property 13",
      "special services": false,
      price: 1700,
      ID: "c4a32e70-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 14",
      description: "Description of Property 14",
      location: "Location of Property 14",
      views: "Views of Property 14",
      technologies: "Technologies of Property 14",
      rooms: 4,
      "extra amenities": "Amenities of Property 14",
      "special services": true,
      price: 1900,
      ID: "c4a32f90-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 15",
      description: "Description of Property 15",
      location: "Location of Property 15",
      views: "Views of Property 15",
      technologies: "Technologies of Property 15",
      rooms: 2,
      "extra amenities": "Amenities of Property 15",
      "special services": true,
      price: 1800,
      ID: "c4a330b0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 16",
      description: "Description of Property 16",
      location: "Location of Property 16",
      views: "Views of Property 16",
      technologies: "Technologies of Property 16",
      rooms: 5,
      "extra amenities": "Amenities of Property 16",
      "special services": false,
      price: 2300,
      ID: "c4a331d0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 17",
      description: "Description of Property 17",
      location: "Location of Property 17",
      views: "Views of Property 17",
      technologies: "Technologies of Property 17",
      rooms: 3,
      "extra amenities": "Amenities of Property 17",
      "special services": false,
      price: 1600,
      ID: "c4a332f0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 18",
      description: "Description of Property 18",
      location: "Location of Property 18",
      views: "Views of Property 18",
      technologies: "Technologies of Property 18",
      rooms: 4,
      "extra amenities": "Amenities of Property 18",
      "special services": true,
      price: 2100,
      ID: "c4a33410-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 19",
      description: "Description of Property 19",
      location: "Location of Property 19",
      views: "Views of Property 19",
      technologies: "Technologies of Property 19",
      rooms: 2,
      "extra amenities": "Amenities of Property 19",
      "special services": true,
      price: 1800,
      ID: "c4a33520-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 20",
      description: "Description of Property 20",
      location: "Location of Property 20",
      views: "Views of Property 20",
      technologies: "Technologies of Property 20",
      rooms: 5,
      "extra amenities": "Amenities of Property 20",
      "special services": false,
      price: 2200,
      ID: "c4a33640-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 21",
      description: "Description of Property 21",
      location: "Location of Property 21",
      views: "Views of Property 21",
      technologies: "Technologies of Property 21",
      rooms: 3,
      "extra amenities": "Amenities of Property 21",
      "special services": false,
      price: 1700,
      ID: "c4a33770-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 22",
      description: "Description of Property 22",
      location: "Location of Property 22",
      views: "Views of Property 22",
      technologies: "Technologies of Property 22",
      rooms: 4,
      "extra amenities": "Amenities of Property 22",
      "special services": true,
      price: 1900,
      ID: "c4a338a0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 23",
      description: "Description of Property 23",
      location: "Location of Property 23",
      views: "Views of Property 23",
      technologies: "Technologies of Property 23",
      rooms: 2,
      "extra amenities": "Amenities of Property 23",
      "special services": true,
      price: 1800,
      ID: "c4a339c0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 24",
      description: "Description of Property 24",
      location: "Location of Property 24",
      views: "Views of Property 24",
      technologies: "Technologies of Property 24",
      rooms: 5,
      "extra amenities": "Amenities of Property 24",
      "special services": false,
      price: 2300,
      ID: "c4a33ae0-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 25",
      description: "Description of Property 25",
      location: "Location of Property 25",
      views: "Views of Property 25",
      technologies: "Technologies of Property 25",
      rooms: 3,
      "extra amenities": "Amenities of Property 25",
      "special services": false,
      price: 1600,
      ID: "c4a33c00-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 26",
      description: "Description of Property 26",
      location: "Location of Property 26",
      views: "Views of Property 26",
      technologies: "Technologies of Property 26",
      rooms: 4,
      "extra amenities": "Amenities of Property 26",
      "special services": true,
      price: 2100,
      ID: "c4a33d20-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 27",
      description: "Description of Property 27",
      location: "Location of Property 27",
      views: "Views of Property 27",
      technologies: "Technologies of Property 27",
      rooms: 2,
      "extra amenities": "Amenities of Property 27",
      "special services": true,
      price: 1800,
      ID: "c4a33e40-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 28",
      description: "Description of Property 28",
      location: "Location of Property 28",
      views: "Views of Property 28",
      technologies: "Technologies of Property 28",
      rooms: 5,
      "extra amenities": "Amenities of Property 28",
      "special services": false,
      price: 2200,
      ID: "c4a33f60-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 29",
      description: "Description of Property 29",
      location: "Location of Property 29",
      views: "Views of Property 29",
      technologies: "Technologies of Property 29",
      rooms: 3,
      "extra amenities": "Amenities of Property 29",
      "special services": false,
      price: 1700,
      ID: "c4a34080-c3f1-11eb-8529-0242ac130003",
    },
    {
      name: "Property 30",
      description: "Description of Property 30",
      location: "Location of Property 30",
      views: "Views of Property 30",
      technologies: "Technologies of Property 30",
      rooms: 5,
      "extra amenities": "Amenities of Property 30",
      "special services": false,
      price: 2500,
      ID: "c4a354a0-c3f1-11eb-8529-0242ac130003",
    },
  ];
  
