export const GET_ALL_PROPERTIES = "GET_ALL_PROPERTIES"
export const GET_DETAIL_USER = 'GET_DETAIL_USER';
export const GET_DETAIL_PROPERTY = 'GET_DETAIL_PROPERTY';
export const NEW_ACCOUNT = "NEW_ACCOUNT"
