export const GET_ALL_PROPERTIES = "GET_ALL_PROPERTIES"
export const SEARCH_PROPERTY = "SEARCH_PROPERTY"
export const GET_DETAIL_USER = 'GET_DETAIL_USER';
export const GET_DETAIL_PROPERTY = 'GET_DETAIL_PROPERTY';
export const GET_DETAIL_CLEAR = 'GET_DETAIL_CLEAR';
export const NEW_ACCOUNT = "NEW_ACCOUNT";
export const NEW_POST = "NEW_POST"

