export const GET_ALL_PROPERTIES = "GET_ALL_PROPERTIES"
export const GET_DETAIL_PROPERTIE = "GET_DETAIL_PROPERTIE"
export const GET_DETAIL_USER = 'GET_DETAIL_USER';
export const GET_DETAIL_PROPERTY = 'GET_DETAIL_PROPERTY';
